target 'XBExtension', :exclusive => true do
  pod "XBExtension", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "XBExtension", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
